'use strict';

/**
 * @ngdoc function
 * @name quoinApp.controller:MainCtrl
 * @description
 * # MainCtrl
 *   Buy passes on main page
 */
angular.module('quoinApp')
  .controller('MainCtrl', function ($scope, passFactory) {
    //placeholder
    $scope.unlimitedAmount = {};

  	//Store Selection variables in scopes incase they ever need to chance
  	$scope.modeOfTransport = [{"id":0,"name":"Bus"},{"id":1,"name":"Subway"},{"id":2,"name":"Commuter Rail"}];

  	$scope.passTypes = [{"id":0,"name":"Monthly"},{"id":1,"name":"Prepaid"}];

    //fetch prices
    $scope.monthlyCosts = passFactory.monlthyCosts();
    
 	/**
	* Purchase Pass click function
	* type (string) = type of pass being purchased (Monthly, Unlimited)
	*/
  	$scope.purchasePass = function(){

      //collecy information from input models on page, for testing we will hardcode
      //NOTE : key 'id' is not included the first generation because it will be generated by server (as a unique id)
      //On Sprint 2 we will generate these from inputs on the page and add validation
      if($scope.typeSelect.id === 0){
        //we would do something like var isStudent = studentCheck ? true : false; to check the inputs
        $scope.myPass = {'type' : 0, 'isElderly' : false, 'isStudent' : false, 'isWorker' : false, 'validBus' : true, 'validSubway' : true, 'validCommuter' : false };
        //alert("Purchased Monthly " + $scope.transportSelect.name + " pass");
     }else if($scope.typeSelect.id === 1){

        var storeAmount = parseFloat($scope.unlimitedAmount.amount).toFixed(2);
        $scope.myPass = {'type' : 1, 'isElderly' : false, 'isStudent' : false, 'isWorker' : false, 'validBus' : true, 'validSubway' : true, 'validCommuter' : false, 'balance' : storeAmount };
        //confirmation
        //alert("Purchased prepaid " + $scope.transportSelect.name + " pass with " + storeAmount + " credit");
      }
    }


  });
